server:
  port: 8087

spring:
  application:
    name: menu-service
  datasource:
    url: jdbc:postgresql://localhost:5434/menu_service
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/master.yaml
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    acks: all
    enable-idempotence: true
    retries: 3
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
    log:
      cleaner:
        enable: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/
  instance:
    prefer-ip-address: true


resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
      eventConsumerBufferSize: 10
      ignoreExceptions:
        - com.example.menuservice.exceptions.MissingException
        - feign.FeignException$BadRequest
  instances:
    userService:
      baseConfig: default
      waitDurationInOpenState: 15s
      failureRateThreshold: 60
    inventoryService:
      baseConfig: default
      waitDurationInOpenState: 15s
      failureRateThreshold: 60

themealdb:
  urlByIngredient: https://www.themealdb.com/api/json/v1/1/filter.php?i=
  urlById: https://www.themealdb.com/api/json/v1/1/lookup.php?i=

calorieninjas:
  url: https://api.calorieninjas.com/v1/nutrition?query=
  key: YmZpIyj/rzey90GJNqX2rg==RNS9RWUrolSJwILI

ollama:
  url: http://localhost:11434/api/generate
  model: llama3.2